In [1]:
import numpy as np

Importing numpy in python and aliasing it as np. So whenever numpy is to be used it can be replaced by np.

# BUILT IN NUMPY FUNCTIONS

## 1 np.array()

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
type(a)

numpy.ndarray

Creating a numpy array using np.array() and within it passing a list. It's datatype is numpy.ndarray

## 2 np.zeros()

In [4]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

It creates a numpy array having all elements zero of dimension 2 * 10 i.e. 2 rows and 10 columns.

In [5]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

It creates a linear array with 6 elements all zeros.

## 3 np.ones()

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

It creates a linear array with 5 elements all initialised to 1.

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

It creates a numpy array with all elements 1 of size 3 * 4 i.e. 3 rows and 4 columns.

## 4 np.empty()

In [8]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [9]:
np.empty((2,4))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 6.50190390e-321, 7.40412294e-278,
        9.84937311e-292]])

np.empty() returns a new array of given shape and type, without initializing entries.

## 5 np.insert()

In [10]:
b = np.arange(6)

In [11]:
np.insert(b,1,1)

array([0, 1, 1, 2, 3, 4, 5])

Here, in b numpy array at index 1 the value 1 is being inserted.

## 6 np.append()

In [11]:
c = np.arange(6)

In [5]:
c = np.append(c,7)

In [6]:
np.append(c,8)

array([0, 1, 2, 3, 4, 5, 7, 8])

Here, element 7 is being added to end of numpy array c

## 7 np.resize()

In [8]:
np.resize(c,(2,3))

array([[0, 1, 2],
       [3, 4, 5]])

Here, the numpy array c is being resized into 2 rows and 3 columns.

## 8 np.delete()

In [9]:
np.delete(c,1)

array([0, 2, 3, 4, 5, 7])

The element at index 1 in numpy array c is being deleted.

## 9 np.split()

In [12]:
np.split(c,3)

[array([0, 1]), array([2, 3]), array([4, 5])]

The split() function have split the original numpy array c into two subarrays of equal length.

## 10 np.ones_like()

In [17]:
b = np.arange(0,12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
np.ones_like(b)        

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

np.ones_like() is used to return an array of ones with the same shape and type as a given array.

## 11 np.empty_like()

In [19]:
d = np.arange(0,6).reshape(2,3)     
d

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
np.empty_like(d)

array([[0, 0, 0],
       [0, 0, 0]])

numpy.empty_like() is used to return a new array with the same shape and type as a given array.

## 12 Transpose of multidimensional numpy array

In [21]:
d = np.arange(0,6).reshape(2,3)     
d

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
d.T

array([[0, 3],
       [1, 4],
       [2, 5]])

Here, the rows and columns have been interchanged by columns and rows respectively.

## 13 np.arange()

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

It displays a linear numpy array with elements starting from 0 till 10 excluding 10.

In [14]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

It displays a numpy array starting from 0 till 100(excluding 100) with a step or increase of 10.

## 14 np.concatenate()

In [15]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]]) 

In [16]:
x

array([[1, 2],
       [3, 4]])

In [17]:
y

array([[5, 6]])

In [28]:
np.concatenate((x, y), axis=0) 

array([[1, 2],
       [3, 4],
       [5, 6]])

Here, the numpy arrays x and y are being concatenated column wise.

In [29]:
np.concatenate((x, y.T), axis=1) 

array([[1, 2, 5],
       [3, 4, 6]])

Initally the transpose of b is taken and then it is concatenated with numpy array x row wise.

In [30]:
np.concatenate((x, y), axis=None) 

array([1, 2, 3, 4, 5, 6])

As, no axis have been mentioned then all the arrays have been converted to a vector.

## 15 np.zeros_like()

In [31]:
e = np.arange(0,6).reshape(2,3)
e

array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
np.zeros_like(e)

array([[0, 0, 0],
       [0, 0, 0]])

np.zeros_like():- It return an array of zeros with the same shape and type as a given array.

## 16 np.random.uniform(start_value, end_value)

In [33]:
np.random.uniform(1,50)

36.612572387995634

In [34]:
np.random.uniform(1,50)

29.83562054746265

It generates a random real number between 1 and 50 and the number generated is unique everytime.

## 17 np.random.randint(start_value, end_value)

In [35]:
np.random.randint(1,60)

50

In [36]:
np.random.randint(1,60)

39

It generates a random integer number between 1 and 60 and each time the number generated is unique.

## 18 np.random.randn(m, n)

In [37]:
np.random.randn(3,4)

array([[ 0.29542244, -0.66957928,  0.72103686, -0.15504839],
       [-0.92980248,  2.70545521, -1.38043349, -0.32382985],
       [-1.16861702,  0.36822234, -1.39094088, -0.32508273]])

It generates a set of random real numbers and store them in an array of 3 rows and 4 columns.  

# PRINTING NUMPY ARRAYS

## 1 Printing linear numpy arrays

In [38]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


## 2 Printing multidimensional arrays.

In [39]:
b = np.arange(15).reshape(3,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# BASIC ARITHMETIC OPERATIONS

In [40]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [41]:
x

array([1, 2, 3, 4])

In [42]:
y

array([5, 6, 7, 8])

## 1 Addition

In [43]:
x + y

array([ 6,  8, 10, 12])

## 2 Subtraction

In [44]:
x - y

array([-4, -4, -4, -4])

## 3 Multiplication

In [45]:
x * y

array([ 5, 12, 21, 32])

## 4 Division

In [46]:
x / y

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

## 5 Integral Division

In [47]:
x // y

array([0, 0, 0, 0], dtype=int32)

In [48]:
y // x

array([5, 3, 2, 2], dtype=int32)

## 6 Modulus Operator

In [49]:
y % x

array([0, 0, 1, 0], dtype=int32)

## 7 Logical Operations

In [50]:
x <5 

array([ True,  True,  True,  True])

## 8 Power Operations

In [51]:
y ** 2

array([25, 36, 49, 64], dtype=int32)

In [52]:
x ** 0.5

array([1.        , 1.41421356, 1.73205081, 2.        ])

## 9 Multidimensional Array multiplication

In [53]:
a = np.array([(1,2),(4,5)])
b = np.array([(7,8),(9,10)])

In [54]:
a

array([[1, 2],
       [4, 5]])

In [55]:
b

array([[ 7,  8],
       [ 9, 10]])

In [56]:
a * b

array([[ 7, 16],
       [36, 50]])

It is simple multiplication which is occurring element wise element

In [57]:
a.dot(b)

array([[25, 28],
       [73, 82]])

It is matrix multiplications

Matrix multiplication [row , column] =  sum(all elements in row * all elements in column

## 10 Unary Operations

In [58]:
x *=2
x

array([2, 4, 6, 8])

In [59]:
x -=1
x

array([1, 3, 5, 7])

Operations like multiplying an element by 2 or incrementing element by 1 falls under unary operations.

## 11 Sum of all elements of a numpy array

In [60]:
x.sum()

16

Sum function in numpy evaluates sum of all elements in numpy array.

## 12 Finding minimum and maximum element in Numpy array

In [61]:
x.min()

1

In [62]:
x.max()

7

The min() function and max() function in numpy evaluates minimum and maximum element respectively in given numpy array.

## 13 Axis in numpy array
#### The axis denotes operations to be performed column-wise or row-wise.

In [63]:
a

array([[1, 2],
       [4, 5]])

In [64]:
a.sum(axis=0)

array([5, 7])

In [65]:
a.sum(axis=1)

array([3, 9])

In [66]:
a.min(axis=0)

array([1, 2])

In [67]:
a.min(axis=1)

array([1, 4])

In [68]:
a.max(axis=0)

array([4, 5])

In [69]:
a.max(axis=1)

array([2, 5])

The axis denotes operations to be performed column-wise or row-wise.
   -  axis = 0    -> perform operation column-wise
   - axis = 1    -> perform operation row-wise


# UNIVERSAL FUNCTIONS IN NUMPY ARRAY

## 1 Pi

In [70]:
angles = np.array([0,10,20,30,40])

In [71]:
radians = angles * np.pi / 180

## 2 Sin

In [72]:
np.sin(angles)

array([ 0.        , -0.54402111,  0.91294525, -0.98803162,  0.74511316])

## 3 Cos

In [73]:
np.cos(angles)

array([ 1.        , -0.83907153,  0.40808206,  0.15425145, -0.66693806])

## 4 Radians

In [74]:
np.radians(angles)

array([0.        , 0.17453293, 0.34906585, 0.52359878, 0.6981317 ])

## 5 Degrees

In [75]:
np.degrees(radians)

array([ 0., 10., 20., 30., 40.])

## 6 Arcsin

In [76]:
np.arcsin(radians)

array([0.        , 0.17543139, 0.35657406, 0.55106958, 0.7727847 ])

## 7 Mean

In [77]:
np.mean(angles)

20.0

## 8 Median

In [78]:
np.median(angles)

20.0

## 9 Std
#### Standard Deviation

In [79]:
np.std(angles)

14.142135623730951

## 10 Tan

In [80]:
np.tan(angles)

array([ 0.        ,  0.64836083,  2.23716094, -6.4053312 , -1.11721493])

# LIST INDEXING AND SLICING

In [81]:
c = [1,6,9,10,12,3,5,7]

### 1 Positive Indexing

In [82]:
c[0]
#Displays first element

1

In [83]:
c[1]
#Displays second element or element at first index

6

### 2 Negative Indexing

In [84]:
c[-1]
#Displays last element or first element from right of array

7

In [85]:
c[-2]
#Displays second last element or second element from right of array

5

### 3 Miscellaneous Operations

In [86]:
c[1:8]
# select all elements from index 1 to 8(excluding element at 8th index)  

[6, 9, 10, 12, 3, 5, 7]

In [87]:
c[:5]
# select all elements from starting i.e. index 0 till 5th index(where 5th  index element is not included) 

[1, 6, 9, 10, 12]

In [88]:
c[3:-3]
# select elements from index 3 till 3rd last element where it is not included     

[10, 12]

In [89]:
c[0:9:2]
#elements starting from index 0 up to index 9(element at 9th index not included) and a step of 2

[1, 9, 12, 5]

In [90]:
c[::-1]
#start from beginning to end with a step or decrement of 1. It simply reverses the array.

[7, 5, 3, 12, 10, 9, 6, 1]

## Indexing in Multi-Dimensional Lists

In [19]:
d = np.array([(1,2,3),(4,5,6),(7,8,9)])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
d[0]
# extracts first row elements from the list    

array([1, 2, 3])

In [93]:
d[-1]
# extracts last row elements from the list    

array([7, 8, 9])

In [94]:
d[0][0]
# extracts first element or zeroth index element or element at first position of first row

1

In [95]:
d[0][0:2]
# select elements in first row from index 0 to 2nd index where 2nd index element is not included

array([1, 2])

# ITERATING OVER NUMPY ARRAYS

### 1 Iterating in single dimensional arrays

In [96]:
e = np.arange(4)
e

array([0, 1, 2, 3])

In [97]:
for i in e:
    print(i)

0
1
2
3


### 2 Iterating in multidimensional dimensional arrays

In [20]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
for i in d.flatten():
    print(i)

1
2
3
4
5
6
7
8
9


flatten() returns a copy of the array collapsed into one dimension.

In [100]:
for j in np.nditer(d):
    print(j)

1
2
3
4
5
6
7
8
9


np.nditer() sets iterator for iterating over each element of multidimensional numpy array.

# RESHAPING NUMPY ARRAYS

In [25]:
f = np.arange(15)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 1 When number of rows and columns are predetermined.

In [26]:
f.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
f.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [28]:
f.reshape(3,4)

ValueError: cannot reshape array of size 15 into shape (3,4)

### 2 When either number of rows or columns are unknown.

In [105]:
f.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Here , number of columns are known to be 5 but rows are unknown so it is denoted by -1

In [106]:
f.reshape(5,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Here , number of rows are known to be 5 but columns are unknown so it is denoted by -1

#### Python automatically determines the missing quantity and fits the data.

# BROADCASTING NUMPY ARRAYS

In [107]:
x

array([1, 3, 5, 7])

In [108]:
z = 3

In [109]:
x * z

array([ 3,  9, 15, 21])

In [32]:
import time

size = 10000000

t1 = time.time()
a = range(size)
b = range(size)
c = [a[i] + b[i] for i in range(len(a))]

print( time.time() - t1)

5.600024461746216


In [33]:

size = 10000000

t1 = time.time()
a = np.arange(size)
b = np.arange(size)
c = a + b

print( time.time() - t1)

0.5145862102508545


The variable z has broadcast to size of numpy array x for multiplication.